# The URL the site will be built for
base_url = "https://massivelive.fun"

title = "Matthew Lance Fuller"
description = "A personal website for showcasing projects and displaying contact information."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_linkes_target_blank = true
smart_punctuation = true
render_emoji = true

[extra]
# Put all your custom variables here
author = "Matthew Lance Fuller"
description = "A personal website for showcasing projects and displaying contact information."

[extra.social]
email = "matthewlancefuller@gmail.com"
twitter = "https://www.twitter.com/massivelivefun"
steam = "https://steamcommunity.com/id/massivelivefun/"
youtube = "https://www.youtube.com/massivelivefun"
stackoverflow = "https://stackoverflow.com/users/7698058/massivelivefun"
soundcloud = "https://www.soundcloud.com/massivelivefun"
github = "https://www.github.com/massivelivefun"
twitch = "https://www.twitch.com/massivelivefun"
spotify = "https://open.spotify.com/user/qbmx6bujstfliuwja28fknwm3"
